# Generated by Django 5.2.7 on 2025-12-03 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0004_category_quiz_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
    ]
