# Generated by Django 5.2.7 on 2025-12-16 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0008_quiz_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='lifelines_used',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
