# Generated by Django 5.2.7 on 2025-12-31 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0011_classpackage_paymenthistory_scheduledclass_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledclass',
            name='packages',
            field=models.ManyToManyField(blank=True, related_name='classes', to='quizzes.classpackage'),
        ),
    ]
